# Valores específicos para el entorno de producción

replicaCount: 3

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: app.contract-ease.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: contract-ease-tls
     hosts:
       - app.contract-ease.com

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

vault:
  enabled: true
  role: "contract-ease-prod"
  secretPath: "secret/data/production/contract-ease"
