environment: local
domain: covalto.local
revision: local
squad: data-group
product: covalto-ai-services
replicas: 1
docker:
  image: us-central1-docker.pkg.dev/covalto-registry-spt/covalto-ai-services/contract-gen-app

ingress:
  public: false


env:
  ENVIRONMENT: '{{ .Values.environment }}'
  PROJECT_NAME: '{{ .Release.Name }}'
  GOOGLE_API_KEY: 'vault:{{ .Values.environment }}/data/{{ .Release.Name }}#GOOGLE_API_KEY'

resources_service:
  request:
    memory: 100Mi
    cpu: 150m
  limits:
    memory: 250Mi
    cpu: 300m