apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}'
  labels:
    app.kubernetes.io/name: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ template "shortRevision" . }}'
    app.kubernetes.io/component: 'application'
    covalto.com/product: '{{ .Values.product }}'
    covalto.com/squad: '{{ .Values.squad }}'
spec:
  ingressClassName: nginx-{{ if .Values.ingress.public }}{{ "public" }}{{ else }}{{ "private" }}{{ end }}
  rules:
    - host: '{{ .Release.Name }}.{{ .Values.domain }}'
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: '{{ .Release.Name }}'
                port:
                  name: 'http'
  tls:
    - hosts:
        - '{{ .Release.Name }}.{{ .Values.domain }}'
