version: 2.1

parameters:
  project-name:
    type: string
    default: 'contract-gen-app'

orbs:
  argocd: credijusto/argocd@volatile
  ssh: credijusto/ssh@volatile
  gcp-gcr: circleci/gcp-gcr@0.15.3
  node: circleci/node@5.2.0

executors:
  default:
    machine:
      image: ubuntu-2204:2024.05.1
      docker_layer_caching: true

jobs:
  validate:
    docker:
      - image: us-central1-docker.pkg.dev/covalto-registry-spt/cli/cli:latest
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    resource_class: small
    steps:
      - checkout
      - ssh/start-tunnel
      - ssh/execute:
          command: cj validate

  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Linter
          command: npm run lint

  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm run test

  build-and-push:
    executor:
      name: default
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          registry-url: us-central1-docker.pkg.dev
      - gcp-gcr/build-image:
          registry-url: us-central1-docker.pkg.dev
          image: covalto-ai-services/<< pipeline.parameters.project-name >>
          tag: ${CIRCLE_SHA1:0:7}
      - gcp-gcr/push-image:
          registry-url: us-central1-docker.pkg.dev
          image: covalto-ai-services/<< pipeline.parameters.project-name >>
          tag: ${CIRCLE_SHA1:0:7}

workflows:
  main:
    jobs:
      - validate:
          context: [gcp-bastion, code-repository, gcp-docker-repository]

      - lint:
          requires: [validate]
          context: [ 'gcp-bastion', 'code-repository', 'gcp-docker-repository' ]

      - test:
          requires: [ 'lint', 'validate' ]
          context: [ 'gcp-bastion', 'code-repository', 'gcp-docker-repository' ]

      - build-and-push:
          requires: [test]
          context: [gcp-bastion, code-repository, gcp-docker-repository]
          filters:
            branches:
              only: [main]

      - argocd/sync:
          requires: [build-and-push]
          context: [gcp-bastion]
          revision: main
          filters:
            branches:
              only: [main]
